/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    PullList: typeof import('./components/pullList.vue')['default']
    RfSearchBar: typeof import('./components/rf-search-bar/index.vue')['default']
    RfSwipeDot: typeof import('./components/rf-swipe-dot/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
